version: '3.8'

services:
  nextjs:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nextjs-dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  nestjs:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nestjs-dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
